spring.application.name=healthcare

spring.datasource.url=jdbc:mysql://prod-db-server:3306/healthcare_test
spring.datasource.username=user
spring.datasource.password=password


app.cache.doctors.expiry-minutes=2
app.cache.doctors.max-size=100
app.cache.patient.expiry-minutes=2
app.cache.patient.max-size=100

app.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktbG9uZy1hbmQtc2VjdXJlLWtleS1mb3ItZGV2LW9ubHkK}
app.jwt.expiration-ms=600000