spring.application.name=healthcare

spring.datasource.url=jdbc:h2:mem:healthcare
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

logging.level.com.kfh.healthcare=DEBUG

app.cache.doctors.expiry-minutes=2
app.cache.doctors.max-size=100
app.cache.patient.expiry-minutes=2
app.cache.patient.max-size=100

app.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktbG9uZy1hbmQtc2VjdXJlLWtleS1mb3ItZGV2LW9ubHkK}
app.jwt.expiration-ms=600000