spring.application.name=healthcare

spring.datasource.url=jdbc:mysql://prod-db-server:3306/healthcare_test
spring.datasource.username=user
spring.datasource.password=password


app.cache.doctors.expiry-minutes=2
app.cache.doctors.max-size=100
app.cache.patient.expiry-minutes=2
app.cache.patient.max-size=100